apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: products
spec:
  selector:
    app: products
  type: NodePort
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31001
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: products
spec:
  selector:
    app: products
  type: NodePort
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 31002
      targetPort: 8080